services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: wp_to_db_user
    secrets:
      - mariadb_root_password
      - wp_to_db_user_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: wp_to_db_user
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: wp_manager_user
      WP_ADMIN_EMAIL: manager@42.fr
      WP_REGULAR_USER: wp_editor_user
      WP_REGULAR_EMAIL: editor@42.fr
    secrets:
      - wp_to_db_user_password
      - wp_manager_password
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
      - ${CERTS_ROOT}/ssl:/etc/ssl/certs
      - ${CERTS_ROOT}/private:/etc/ssl/private
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception_net


volumes:
  db:
  wp:

networks:
  inception_net:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_root_password.txt
  wp_to_db_user_password:
    file: ${PROJECT_ROOT}/secrets/wp_to_db_user_password.txt
  wp_manager_password:
    file: ${PROJECT_ROOT}/secrets/wp_manager_password.txt
  wp_editor_password:
    file: ${PROJECT_ROOT}/secrets/wp_editor_password.txt
  wp_manager_user:
    file: ${PROJECT_ROOT}/secrets/wp_manager_user.txt
  wp_editor_user:
    file: ${PROJECT_ROOT}/secrets/wp_editor_user.txt
