services:
  # -----------------------------
  #      MariaDB Database SERVICE
  # -----------------------------
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: wp_to_db_user
    secrets:
      - mariadb_root_password
      - wp_to_db_user_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net

  # -----------------------------
  #             WordPress SERVICE
  # -----------------------------
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_REGULAR_USER: ${WORDPRESS_REGULAR_USER}
      WORDPRESS_REGULAR_EMAIL: ${WORDPRESS_REGULAR_EMAIL}
    secrets:
      - wp_to_db_user_password
      - wp_manager_password
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net

  # -----------------------------
  #      Nginx Web Server SERVICE
  # -----------------------------
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
      - ./certs/frromero.42.fr.crt:/etc/ssl/certs/frromero.42.fr.crt:ro
      - ./certs/frromero.42.fr.key:/etc/ssl/private/frromero.42.fr.key:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inception_net

  #-----------------------------
  #    Bonus: Static Web SERVICE 
  #-----------------------------
  static-web:
    build: ./requirements/bonus/static-web
    image: static-web
    container_name: static-web
    restart: always
    profiles: ["bonus"]
    ports:
      - "8080:8080"
    volumes:
      - ./certs/frromero.42.fr.crt:/etc/ssl/certs/frromero.42.fr.crt:ro
      - ./certs/frromero.42.fr.key:/etc/ssl/private/frromero.42.fr.key:ro
    networks:
      - inception_net

# -----------------------------
# Docker Volumes
# -----------------------------
volumes:
  db:
  wp:

# -----------------------------
# Docker Networks
# -----------------------------
networks:
  inception_net:
    driver: bridge

# -----------------------------
# Docker Secrets
# -----------------------------
secrets:
  mariadb_root_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_root_password.txt
  wp_to_db_user_password:
    file: ${PROJECT_ROOT}/secrets/wp_to_db_user_password.txt
  wp_manager_password:
    file: ${PROJECT_ROOT}/secrets/wp_manager_password.txt
  wp_editor_password:
    file: ${PROJECT_ROOT}/secrets/wp_editor_password.txt
  wp_manager_user:
    file: ${PROJECT_ROOT}/secrets/wp_manager_user.txt
  wp_editor_user:
    file: ${PROJECT_ROOT}/secrets/wp_editor_user.txt
