services:
  #      MariaDB Database SERVICE
  # -----------------------------
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p$$MARIADB_ROOT_PASSWORD -e 'SELECT 1;' || exit 1"]
      start_period: 30s
      interval: 15s
      timeout: 10s
      retries: 3
      
  #             WordPress SERVICE
  # -----------------------------
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
    secrets:
      - mariadb_user_password
      - wp_manager_password
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  #      Nginx Web Server SERVICE
  # -----------------------------
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
      - ${SECRETS_ROOT}/certs/frromero.42.fr.crt:/etc/ssl/certs/frromero.42.fr.crt:ro
      - ${SECRETS_ROOT}/certs/frromero.42.fr.key:/etc/ssl/private/frromero.42.fr.key:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inception_net
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  #    1 - Bonus: Static Web SERVICE
  #-----------------------------
  static-web:
    build: ./requirements/bonus/static-web
    image: static-web
    container_name: static-web
    restart: always
    profiles: [bonus]
    ports:
      - "8080:8080"
    volumes:
      - ${SECRETS_ROOT}/certs/frromero.42.fr.crt:/etc/ssl/certs/frromero.42.fr.crt:ro
      - ${SECRETS_ROOT}/certs/frromero.42.fr.key:/etc/ssl/private/frromero.42.fr.key:ro
    networks:
      - inception_net

  #    2 - Bonus: adminer SERVICE
  #-----------------------------
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    profiles: [bonus]
    networks:
      - inception_net

# Docker Volumes
# -----------------------------
volumes:
  db:
  wp:
  portainer_data:

# Docker Networks
# -----------------------------
networks:
  inception_net:
    driver: bridge

# Docker Secrets
# -----------------------------
secrets:
  mariadb_root_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_root_password.txt
  mariadb_user_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_user_password.txt
  wp_manager_password:
    file: ${PROJECT_ROOT}/secrets/wp_manager_password.txt
  wp_editor_password:
    file: ${PROJECT_ROOT}/secrets/wp_editor_password.txt
  portainer_password:
    file: ${PROJECT_ROOT}/secrets/portainer_password.txt