services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
    secrets:
      - db_root_password
      - db_wp_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_REGULAR_USER: ${WP_REGULAR_USER}
      WP_REGULAR_EMAIL: ${WP_REGULAR_EMAIL}
    secrets:
      - db_wp_password
      - wp_admin_password
      - wp_regular_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net

volumes:
  db:
  wp:

networks:
  inception_net:
    driver: bridge

secrets:
  db_root_password:
    file: ${PROJECT_ROOT}/secrets/db_root_password.txt
  db_wp_password:
    file: ${PROJECT_ROOT}/secrets/db_wp_password.txt
  wp_admin_password:
    file: ${PROJECT_ROOT}/secrets/wp_admin_password.txt
  wp_regular_password:
    file: ${PROJECT_ROOT}/secrets/wp_regular_password.txt
