services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: wpuser
    secrets:
      - mariadb_root_password
      - wpuser_db_password
      - wp_manager_user
      - wp_manager_password
      - wp_editor_user
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: wpuser
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: wp_manager_user
      WP_ADMIN_EMAIL: manager@42.fr
      WP_REGULAR_USER: wp_editor_user
      WP_REGULAR_EMAIL: editor@42.fr
    secrets:
      - wpuser_db_password
      - wp_manager_password
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net

volumes:
  db:
  wp:

networks:
  inception_net:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_root_password.txt
  wpuser_db_password:
    file: ${PROJECT_ROOT}/secrets/wpuser_db_password.txt
  wp_manager_password:
    file: ${PROJECT_ROOT}/secrets/wp_manager_password.txt
  wp_editor_password:
    file: ${PROJECT_ROOT}/secrets/wp_editor_password.txt
  wp_manager_user:
    file: ${PROJECT_ROOT}/secrets/wp_manager_user.txt
  wp_editor_user:
    file: ${PROJECT_ROOT}/secrets/wp_editor_user.txt
